spring.application.name=treeshopmanagingsystem
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:example}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.address=0.0.0.0
server.port=${SERVER_PORT:8080}

# JWT config
#TODO remove when migrating to docker
jwt.secret=a-string-for-testing
jwt.lifetime=86400
jwt.cookie.name=hihi