spring.application.name=treeshopmanagingsystem
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:example}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.address=0.0.0.0
server.port=${SERVER_PORT:8080}

# JWT config
jwt.secret=${JWT_SECRET:a-string-for-testing}
jwt.lifetime=${JWT_LIFETIME:86400}
jwt.cookie.name=${JWT_COOKIE_NAME:hihi}
