spring.application.name=treeshopmanagingsystem
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app}
spring.datasource.username=${POSTGRES_USER:sa}
spring.datasource.password=${POSTGRES_PASSWORD:12345}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
JWT_SECRET=${JWT_SECRET:a-string-for-testing}
JWT_LIFETIME=${JWT_LIFETIME:86400}
server.address=0.0.0.0
server.port=${SERVER_PORT:8081}